# Generated by Django 4.1.3 on 2023-01-21 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arch', '0002_project_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_date', models.DateField()),
                ('design_images', models.ImageField(upload_to='design_images')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arch.project')),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
